import eslintConfigTrumpet from "@trumpet/eslint-config-next";

export default [
    {
        ignores: ["*.config.mjs", "next-env.d.ts", ".next/**", "node_modules/**"],
    },
    ...eslintConfigTrumpet,
    // other configurations below, for example:
    {
        rules: {
            "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
            "@typescript-eslint/consistent-type-imports": "warn",
            "@typescript-eslint/dot-notation": "off",
            "@typescript-eslint/no-deprecated": "off",
            "@typescript-eslint/no-empty-object-type": "off",
            "@typescript-eslint/no-explicit-any": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-argument": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-confusing-void-expression": "off",
            "@typescript-eslint/no-floating-promises": "off",
            "@typescript-eslint/no-invalid-void-type": "off",
            "@typescript-eslint/no-unnecessary-condition": "off",
            "@typescript-eslint/no-unnecessary-type-conversion": "off",
            "@typescript-eslint/prefer-nullish-coalescing": "off",
            "@typescript-eslint/prefer-promise-reject-errors": "off",
            "@typescript-eslint/require-await": "off",
            "@typescript-eslint/return-await": "off",
            "@typescript-eslint/switch-exhaustiveness-check": "off",
            "@typescript-eslint/use-unknown-in-catch-callback-variable": "off",
            "curly": "off",
            "jsx-a11y/click-events-have-key-events": "off",
            "jsx-a11y/heading-has-content": "off",
            "jsx-a11y/label-has-associated-control": "off",
            "jsx-a11y/no-autofocus": "off",
            "jsx-a11y/no-static-element-interactions": "off",
            "n/no-unsupported-features/es-syntax": "off",
            "no-console": "warn",
            "prefer-destructuring": "off",
            "promise/always-return": "off",
            "promise/no-promise-in-callback": "off",
            "react/no-unknown-property": "off",
            "react/no-unescaped-entities": "off",
            "perfectionist/sort-exports": "off",
            "perfectionist/sort-interfaces": "off",
            "perfectionist/sort-intersection-types": "off",
            "perfectionist/sort-jsx-props": "off",
            "perfectionist/sort-modules": "off",
            "perfectionist/sort-named-imports": "off",
            "perfectionist/sort-object-types": "off",
            "perfectionist/sort-objects": "off",
            "perfectionist/sort-switch-case": "off",
            "perfectionist/sort-union-types": "off",
            "unicorn/consistent-function-scoping": "off",
            "unicorn/filename-case": "off",
            "unicorn/no-empty-file": "off",
            "unicorn/no-nested-ternary": "off",
            "unicorn/no-useless-promise-resolve-reject": "off",
            "unicorn/numeric-separators-style": "off",
            "unicorn/prefer-at": "off",
            "unicorn/prefer-code-point": "off",
            "unicorn/prefer-global-this": "off",
            "unicorn/prefer-number-properties": "off",
            "unicorn/prefer-string-slice": "off",
            "unicorn/prefer-switch": "off",
            "unicorn/switch-case-braces": "off",
            "unused-imports/no-unused-imports": "off",
        },
    },
];
